service: spens

image: daviddossou/spens

servers:
  web:
    - 46.62.157.51

proxy:
  ssl: true
  host: spens.me

registry:
  server: ghcr.io
  username: daviddossou
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - SPENS_DATABASE_PASSWORD
  clear:
    SOLID_QUEUE_IN_PUMA: true
    DB_HOST: spens-db

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "spens_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64

ssh:
  user: david

accessories:
  db:
    image: postgres:16
    host: 46.62.157.51
    port: "127.0.0.1:5432:5432"
    env:
      clear:
        POSTGRES_USER: spens
        POSTGRES_DB: spens_production
      secret:
        - POSTGRES_PASSWORD
    files:
      - db/production_init.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - data:/var/lib/postgresql/data
